import type { NextPage } from "next"
import Head from "next/head"
import styles from "@styles/Home.module.scss"

import { Header } from "@components/Header"

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>saizaax.dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <h1 className={styles.title}>saizaax.dev</h1>
      </main>
    </div>
  )
}

export default Home
